services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aplikasipegawai-app
    container_name: aplikasipegawai-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVER_NAME: :80
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - payroll-network

  db:
    image: postgres:15-alpine
    container_name: aplikasipegawai-db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: aplikasipegawai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aplikasipegawai"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payroll-network

  redis:
    image: redis:alpine
    container_name: aplikasipegawai-redis
    restart: unless-stopped
    networks:
      - payroll-network

networks:
  payroll-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
