services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: aplikasipegawai-prod-app
    container_name: aplikasipegawai-prod-app
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - payroll-network

  db:
    image: postgres:15-alpine
    container_name: aplikasipegawai-prod-db
    restart: always
    environment:
      POSTGRES_DB: aplikasipegawai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - dbdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aplikasipegawai"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payroll-network

  redis:
    image: redis:alpine
    container_name: aplikasipegawai-prod-redis
    restart: always
    networks:
      - payroll-network

networks:
  payroll-network:
    driver: bridge

volumes:
  dbdata_prod:
    driver: local
